CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 accelerate launch --config_file configs/default_config.yaml distill.py \
    --teacher_generation_dataset_path /home/ksshumab/minrui/Data-New/Alpaca/generated/alpaca-llama2-13b-finetune-1e-5-text2text-90.jsonl \
    --per_device_train_batch_size 32 \
    --num_train_epochs 4 \
    --student_name meta-llama/Llama-2-7b-hf \
    --output_dir "./output_dir/alpaca/alpaca_llama2-7b_linear-label_smoothing-4e-5-text2text-90/" \
    --wandb_name "alpaca_llama2-7b_linear-label_smoothing-4e-5-text2text-90" \
    --gradient_checkpointing \
    --eps 1e-8 \
    --learning_rate 4e-5 \
    --method forward_kl_text2text \
    --use_norm linear \
    --norm_epsilon 1e-6 \
    --use_label_smoothing yes \
    --smoothing_factor 0.1 \
    --student_temp 0.28 \
    --teacher_temp 0.28 \